package entitie;
// Generated 02-oct-2015 16:45:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Calle generated by hbm2java
 */
@Entity
@Table(name="calle"
    ,schema="public"
)
public class Calle  implements java.io.Serializable {


     private int idCalle;
     private String nombre;
     private String estado;
     private Set<MunicipioCalle> municipioCalles = new HashSet<MunicipioCalle>(0);
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Calle() {
    }

	
    public Calle(int idCalle) {
        this.idCalle = idCalle;
    }
    public Calle(int idCalle, String nombre, String estado, Set<MunicipioCalle> municipioCalles, Set<Direccion> direccions) {
       this.idCalle = idCalle;
       this.nombre = nombre;
       this.estado = estado;
       this.municipioCalles = municipioCalles;
       this.direccions = direccions;
    }
   
     @Id 

    
    @Column(name="id_calle", unique=true, nullable=false)
    public int getIdCalle() {
        return this.idCalle;
    }
    
    public void setIdCalle(int idCalle) {
        this.idCalle = idCalle;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="estado")
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="calle")
    public Set<MunicipioCalle> getMunicipioCalles() {
        return this.municipioCalles;
    }
    
    public void setMunicipioCalles(Set<MunicipioCalle> municipioCalles) {
        this.municipioCalles = municipioCalles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="calle")
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


