package entitie;
// Generated 02-oct-2015 16:45:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name="direccion"
    ,schema="public"
)
public class Direccion  implements java.io.Serializable {


     private int idDireccion;
     private Calle calle;
     private Persona persona;
     private Integer numero;
     private Integer piso;
     private Character puerta;
     private Character letra;
     private String estado;

    public Direccion() {
    }

	
    public Direccion(int idDireccion, Calle calle, Persona persona) {
        this.idDireccion = idDireccion;
        this.calle = calle;
        this.persona = persona;
    }
    public Direccion(int idDireccion, Calle calle, Persona persona, Integer numero, Integer piso, Character puerta, Character letra, String estado) {
       this.idDireccion = idDireccion;
       this.calle = calle;
       this.persona = persona;
       this.numero = numero;
       this.piso = piso;
       this.puerta = puerta;
       this.letra = letra;
       this.estado = estado;
    }
   
     @Id 

    
    @Column(name="id_direccion", unique=true, nullable=false)
    public int getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_calle", nullable=false)
    public Calle getCalle() {
        return this.calle;
    }
    
    public void setCalle(Calle calle) {
        this.calle = calle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_persona", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    
    @Column(name="piso")
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }

    
    @Column(name="puerta", length=1)
    public Character getPuerta() {
        return this.puerta;
    }
    
    public void setPuerta(Character puerta) {
        this.puerta = puerta;
    }

    
    @Column(name="letra", length=1)
    public Character getLetra() {
        return this.letra;
    }
    
    public void setLetra(Character letra) {
        this.letra = letra;
    }

    
    @Column(name="estado")
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


