package entitie;
// Generated 02-oct-2015 16:45:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Maestro generated by hbm2java
 */
@Entity
@Table(name="maestro"
    ,schema="public"
)
public class Maestro  implements java.io.Serializable {


     private int leNumero;
     private Short leCodreg;
     private Integer lePatron;
     private String leApynom;
     private Integer leTarjeta;
     private Integer leFecnac;
     private Long leDocNro;
     private Short leDocTipo;
     private String leCalle;
     private Short lePuerta;
     private String leCiudad;
     private Short leCodpos;
     private Short leNacion;
     private String leECivil;
     private String leSexo;
     private Integer leIngreso;
     private Integer leEgreso;
     private Integer leAntiguedad;
     private Integer leCcosto;
     private Short leTurno;
     private Short leSituacion;
     private String leCodFun;
     private Integer leCCargo;
     private Short leConvenio;
     private Short leFPago;
     private BigDecimal leBasico1;
     private BigDecimal leBasico2;
     private BigDecimal leBasico3;
     private BigDecimal leBasico4;
     private Integer leSubsid;
     private Integer lePrenatal;
     private Short leTitulo;
     private Short leZona;
     private Short leInsalubre;
     private Short leCodJub;
     private Long leNroJub;
     private Short leVcodOsoc;
     private Short leOsocAdic;
     private Short leGremio;
     private Short leSeguro1;
     private Short leSeguro2;
     private Integer leDiasTrabjados;
     private BigDecimal leMejorBasico;
     private BigDecimal leSuplementos;
     private Short leCuilDav;
     private Short leCuilCod;
     private Short leModoLiq;
     private Long leCtaParte1;
     private Short leAfjp;
     private Integer leAdherente;
     private Integer leCodOsoc;
     private BigDecimal leAfjpVol;
     private BigDecimal leSemSfam;
     private Short leCodGananc;
     private Short leCodAccidente;
     private BigDecimal leImpCuota;
     private Integer leOrigenPrest;
     private Short leOtros;
     private Short leOtros1;
     private Short leBanco;
     private Short leTipoCta;
     private Long leNroCta;
     private Integer leUltIngreso;
     private Integer leVtoContrat;
     private Short leEstado;
     private Short leEstadoTrabaja;
     private Integer leDesdeX;
     private Integer leHastaX;
     private Short leMaternidad;
     private String leTurnoFijo;
     private Short leCodUniforme;
     private Short leProrrata;
     private BigDecimal leVacacPagas;
     private Short lePagoSfam;

    public Maestro() {
    }

	
    public Maestro(int leNumero) {
        this.leNumero = leNumero;
    }
    public Maestro(int leNumero, Short leCodreg, Integer lePatron, String leApynom, Integer leTarjeta, Integer leFecnac, Long leDocNro, Short leDocTipo, String leCalle, Short lePuerta, String leCiudad, Short leCodpos, Short leNacion, String leECivil, String leSexo, Integer leIngreso, Integer leEgreso, Integer leAntiguedad, Integer leCcosto, Short leTurno, Short leSituacion, String leCodFun, Integer leCCargo, Short leConvenio, Short leFPago, BigDecimal leBasico1, BigDecimal leBasico2, BigDecimal leBasico3, BigDecimal leBasico4, Integer leSubsid, Integer lePrenatal, Short leTitulo, Short leZona, Short leInsalubre, Short leCodJub, Long leNroJub, Short leVcodOsoc, Short leOsocAdic, Short leGremio, Short leSeguro1, Short leSeguro2, Integer leDiasTrabjados, BigDecimal leMejorBasico, BigDecimal leSuplementos, Short leCuilDav, Short leCuilCod, Short leModoLiq, Long leCtaParte1, Short leAfjp, Integer leAdherente, Integer leCodOsoc, BigDecimal leAfjpVol, BigDecimal leSemSfam, Short leCodGananc, Short leCodAccidente, BigDecimal leImpCuota, Integer leOrigenPrest, Short leOtros, Short leOtros1, Short leBanco, Short leTipoCta, Long leNroCta, Integer leUltIngreso, Integer leVtoContrat, Short leEstado, Short leEstadoTrabaja, Integer leDesdeX, Integer leHastaX, Short leMaternidad, String leTurnoFijo, Short leCodUniforme, Short leProrrata, BigDecimal leVacacPagas, Short lePagoSfam) {
       this.leNumero = leNumero;
       this.leCodreg = leCodreg;
       this.lePatron = lePatron;
       this.leApynom = leApynom;
       this.leTarjeta = leTarjeta;
       this.leFecnac = leFecnac;
       this.leDocNro = leDocNro;
       this.leDocTipo = leDocTipo;
       this.leCalle = leCalle;
       this.lePuerta = lePuerta;
       this.leCiudad = leCiudad;
       this.leCodpos = leCodpos;
       this.leNacion = leNacion;
       this.leECivil = leECivil;
       this.leSexo = leSexo;
       this.leIngreso = leIngreso;
       this.leEgreso = leEgreso;
       this.leAntiguedad = leAntiguedad;
       this.leCcosto = leCcosto;
       this.leTurno = leTurno;
       this.leSituacion = leSituacion;
       this.leCodFun = leCodFun;
       this.leCCargo = leCCargo;
       this.leConvenio = leConvenio;
       this.leFPago = leFPago;
       this.leBasico1 = leBasico1;
       this.leBasico2 = leBasico2;
       this.leBasico3 = leBasico3;
       this.leBasico4 = leBasico4;
       this.leSubsid = leSubsid;
       this.lePrenatal = lePrenatal;
       this.leTitulo = leTitulo;
       this.leZona = leZona;
       this.leInsalubre = leInsalubre;
       this.leCodJub = leCodJub;
       this.leNroJub = leNroJub;
       this.leVcodOsoc = leVcodOsoc;
       this.leOsocAdic = leOsocAdic;
       this.leGremio = leGremio;
       this.leSeguro1 = leSeguro1;
       this.leSeguro2 = leSeguro2;
       this.leDiasTrabjados = leDiasTrabjados;
       this.leMejorBasico = leMejorBasico;
       this.leSuplementos = leSuplementos;
       this.leCuilDav = leCuilDav;
       this.leCuilCod = leCuilCod;
       this.leModoLiq = leModoLiq;
       this.leCtaParte1 = leCtaParte1;
       this.leAfjp = leAfjp;
       this.leAdherente = leAdherente;
       this.leCodOsoc = leCodOsoc;
       this.leAfjpVol = leAfjpVol;
       this.leSemSfam = leSemSfam;
       this.leCodGananc = leCodGananc;
       this.leCodAccidente = leCodAccidente;
       this.leImpCuota = leImpCuota;
       this.leOrigenPrest = leOrigenPrest;
       this.leOtros = leOtros;
       this.leOtros1 = leOtros1;
       this.leBanco = leBanco;
       this.leTipoCta = leTipoCta;
       this.leNroCta = leNroCta;
       this.leUltIngreso = leUltIngreso;
       this.leVtoContrat = leVtoContrat;
       this.leEstado = leEstado;
       this.leEstadoTrabaja = leEstadoTrabaja;
       this.leDesdeX = leDesdeX;
       this.leHastaX = leHastaX;
       this.leMaternidad = leMaternidad;
       this.leTurnoFijo = leTurnoFijo;
       this.leCodUniforme = leCodUniforme;
       this.leProrrata = leProrrata;
       this.leVacacPagas = leVacacPagas;
       this.lePagoSfam = lePagoSfam;
    }
   
     @Id 

    
    @Column(name="le_numero", unique=true, nullable=false)
    public int getLeNumero() {
        return this.leNumero;
    }
    
    public void setLeNumero(int leNumero) {
        this.leNumero = leNumero;
    }

    
    @Column(name="le_codreg")
    public Short getLeCodreg() {
        return this.leCodreg;
    }
    
    public void setLeCodreg(Short leCodreg) {
        this.leCodreg = leCodreg;
    }

    
    @Column(name="le_patron")
    public Integer getLePatron() {
        return this.lePatron;
    }
    
    public void setLePatron(Integer lePatron) {
        this.lePatron = lePatron;
    }

    
    @Column(name="le_apynom", length=30)
    public String getLeApynom() {
        return this.leApynom;
    }
    
    public void setLeApynom(String leApynom) {
        this.leApynom = leApynom;
    }

    
    @Column(name="le_tarjeta")
    public Integer getLeTarjeta() {
        return this.leTarjeta;
    }
    
    public void setLeTarjeta(Integer leTarjeta) {
        this.leTarjeta = leTarjeta;
    }

    
    @Column(name="le_fecnac")
    public Integer getLeFecnac() {
        return this.leFecnac;
    }
    
    public void setLeFecnac(Integer leFecnac) {
        this.leFecnac = leFecnac;
    }

    
    @Column(name="le_doc_nro", precision=10, scale=0)
    public Long getLeDocNro() {
        return this.leDocNro;
    }
    
    public void setLeDocNro(Long leDocNro) {
        this.leDocNro = leDocNro;
    }

    
    @Column(name="le_doc_tipo")
    public Short getLeDocTipo() {
        return this.leDocTipo;
    }
    
    public void setLeDocTipo(Short leDocTipo) {
        this.leDocTipo = leDocTipo;
    }

    
    @Column(name="le_calle", length=24)
    public String getLeCalle() {
        return this.leCalle;
    }
    
    public void setLeCalle(String leCalle) {
        this.leCalle = leCalle;
    }

    
    @Column(name="le_puerta")
    public Short getLePuerta() {
        return this.lePuerta;
    }
    
    public void setLePuerta(Short lePuerta) {
        this.lePuerta = lePuerta;
    }

    
    @Column(name="le_ciudad", length=17)
    public String getLeCiudad() {
        return this.leCiudad;
    }
    
    public void setLeCiudad(String leCiudad) {
        this.leCiudad = leCiudad;
    }

    
    @Column(name="le_codpos")
    public Short getLeCodpos() {
        return this.leCodpos;
    }
    
    public void setLeCodpos(Short leCodpos) {
        this.leCodpos = leCodpos;
    }

    
    @Column(name="le_nacion")
    public Short getLeNacion() {
        return this.leNacion;
    }
    
    public void setLeNacion(Short leNacion) {
        this.leNacion = leNacion;
    }

    
    @Column(name="le_e_civil", length=1)
    public String getLeECivil() {
        return this.leECivil;
    }
    
    public void setLeECivil(String leECivil) {
        this.leECivil = leECivil;
    }

    
    @Column(name="le_sexo", length=1)
    public String getLeSexo() {
        return this.leSexo;
    }
    
    public void setLeSexo(String leSexo) {
        this.leSexo = leSexo;
    }

    
    @Column(name="le_ingreso")
    public Integer getLeIngreso() {
        return this.leIngreso;
    }
    
    public void setLeIngreso(Integer leIngreso) {
        this.leIngreso = leIngreso;
    }

    
    @Column(name="le_egreso")
    public Integer getLeEgreso() {
        return this.leEgreso;
    }
    
    public void setLeEgreso(Integer leEgreso) {
        this.leEgreso = leEgreso;
    }

    
    @Column(name="le_antiguedad")
    public Integer getLeAntiguedad() {
        return this.leAntiguedad;
    }
    
    public void setLeAntiguedad(Integer leAntiguedad) {
        this.leAntiguedad = leAntiguedad;
    }

    
    @Column(name="le_ccosto")
    public Integer getLeCcosto() {
        return this.leCcosto;
    }
    
    public void setLeCcosto(Integer leCcosto) {
        this.leCcosto = leCcosto;
    }

    
    @Column(name="le_turno")
    public Short getLeTurno() {
        return this.leTurno;
    }
    
    public void setLeTurno(Short leTurno) {
        this.leTurno = leTurno;
    }

    
    @Column(name="le_situacion")
    public Short getLeSituacion() {
        return this.leSituacion;
    }
    
    public void setLeSituacion(Short leSituacion) {
        this.leSituacion = leSituacion;
    }

    
    @Column(name="le_cod_fun", length=20)
    public String getLeCodFun() {
        return this.leCodFun;
    }
    
    public void setLeCodFun(String leCodFun) {
        this.leCodFun = leCodFun;
    }

    
    @Column(name="le_c_cargo")
    public Integer getLeCCargo() {
        return this.leCCargo;
    }
    
    public void setLeCCargo(Integer leCCargo) {
        this.leCCargo = leCCargo;
    }

    
    @Column(name="le_convenio")
    public Short getLeConvenio() {
        return this.leConvenio;
    }
    
    public void setLeConvenio(Short leConvenio) {
        this.leConvenio = leConvenio;
    }

    
    @Column(name="le_f_pago")
    public Short getLeFPago() {
        return this.leFPago;
    }
    
    public void setLeFPago(Short leFPago) {
        this.leFPago = leFPago;
    }

    
    @Column(name="le_basico1", precision=10)
    public BigDecimal getLeBasico1() {
        return this.leBasico1;
    }
    
    public void setLeBasico1(BigDecimal leBasico1) {
        this.leBasico1 = leBasico1;
    }

    
    @Column(name="le_basico2", precision=10)
    public BigDecimal getLeBasico2() {
        return this.leBasico2;
    }
    
    public void setLeBasico2(BigDecimal leBasico2) {
        this.leBasico2 = leBasico2;
    }

    
    @Column(name="le_basico3", precision=10)
    public BigDecimal getLeBasico3() {
        return this.leBasico3;
    }
    
    public void setLeBasico3(BigDecimal leBasico3) {
        this.leBasico3 = leBasico3;
    }

    
    @Column(name="le_basico4", precision=10)
    public BigDecimal getLeBasico4() {
        return this.leBasico4;
    }
    
    public void setLeBasico4(BigDecimal leBasico4) {
        this.leBasico4 = leBasico4;
    }

    
    @Column(name="le_subsid")
    public Integer getLeSubsid() {
        return this.leSubsid;
    }
    
    public void setLeSubsid(Integer leSubsid) {
        this.leSubsid = leSubsid;
    }

    
    @Column(name="le_prenatal")
    public Integer getLePrenatal() {
        return this.lePrenatal;
    }
    
    public void setLePrenatal(Integer lePrenatal) {
        this.lePrenatal = lePrenatal;
    }

    
    @Column(name="le_titulo")
    public Short getLeTitulo() {
        return this.leTitulo;
    }
    
    public void setLeTitulo(Short leTitulo) {
        this.leTitulo = leTitulo;
    }

    
    @Column(name="le_zona")
    public Short getLeZona() {
        return this.leZona;
    }
    
    public void setLeZona(Short leZona) {
        this.leZona = leZona;
    }

    
    @Column(name="le_insalubre")
    public Short getLeInsalubre() {
        return this.leInsalubre;
    }
    
    public void setLeInsalubre(Short leInsalubre) {
        this.leInsalubre = leInsalubre;
    }

    
    @Column(name="le_cod_jub")
    public Short getLeCodJub() {
        return this.leCodJub;
    }
    
    public void setLeCodJub(Short leCodJub) {
        this.leCodJub = leCodJub;
    }

    
    @Column(name="le_nro_jub", precision=10, scale=0)
    public Long getLeNroJub() {
        return this.leNroJub;
    }
    
    public void setLeNroJub(Long leNroJub) {
        this.leNroJub = leNroJub;
    }

    
    @Column(name="le_vcod_osoc")
    public Short getLeVcodOsoc() {
        return this.leVcodOsoc;
    }
    
    public void setLeVcodOsoc(Short leVcodOsoc) {
        this.leVcodOsoc = leVcodOsoc;
    }

    
    @Column(name="le_osoc_adic")
    public Short getLeOsocAdic() {
        return this.leOsocAdic;
    }
    
    public void setLeOsocAdic(Short leOsocAdic) {
        this.leOsocAdic = leOsocAdic;
    }

    
    @Column(name="le_gremio")
    public Short getLeGremio() {
        return this.leGremio;
    }
    
    public void setLeGremio(Short leGremio) {
        this.leGremio = leGremio;
    }

    
    @Column(name="le_seguro1")
    public Short getLeSeguro1() {
        return this.leSeguro1;
    }
    
    public void setLeSeguro1(Short leSeguro1) {
        this.leSeguro1 = leSeguro1;
    }

    
    @Column(name="le_seguro2")
    public Short getLeSeguro2() {
        return this.leSeguro2;
    }
    
    public void setLeSeguro2(Short leSeguro2) {
        this.leSeguro2 = leSeguro2;
    }

    
    @Column(name="le_dias_trabjados")
    public Integer getLeDiasTrabjados() {
        return this.leDiasTrabjados;
    }
    
    public void setLeDiasTrabjados(Integer leDiasTrabjados) {
        this.leDiasTrabjados = leDiasTrabjados;
    }

    
    @Column(name="le_mejor_basico", precision=10)
    public BigDecimal getLeMejorBasico() {
        return this.leMejorBasico;
    }
    
    public void setLeMejorBasico(BigDecimal leMejorBasico) {
        this.leMejorBasico = leMejorBasico;
    }

    
    @Column(name="le_suplementos", precision=10)
    public BigDecimal getLeSuplementos() {
        return this.leSuplementos;
    }
    
    public void setLeSuplementos(BigDecimal leSuplementos) {
        this.leSuplementos = leSuplementos;
    }

    
    @Column(name="le_cuil_dav")
    public Short getLeCuilDav() {
        return this.leCuilDav;
    }
    
    public void setLeCuilDav(Short leCuilDav) {
        this.leCuilDav = leCuilDav;
    }

    
    @Column(name="le_cuil_cod")
    public Short getLeCuilCod() {
        return this.leCuilCod;
    }
    
    public void setLeCuilCod(Short leCuilCod) {
        this.leCuilCod = leCuilCod;
    }

    
    @Column(name="le_modo_liq")
    public Short getLeModoLiq() {
        return this.leModoLiq;
    }
    
    public void setLeModoLiq(Short leModoLiq) {
        this.leModoLiq = leModoLiq;
    }

    
    @Column(name="le_cta_parte_1", precision=10, scale=0)
    public Long getLeCtaParte1() {
        return this.leCtaParte1;
    }
    
    public void setLeCtaParte1(Long leCtaParte1) {
        this.leCtaParte1 = leCtaParte1;
    }

    
    @Column(name="le_afjp")
    public Short getLeAfjp() {
        return this.leAfjp;
    }
    
    public void setLeAfjp(Short leAfjp) {
        this.leAfjp = leAfjp;
    }

    
    @Column(name="le_adherente")
    public Integer getLeAdherente() {
        return this.leAdherente;
    }
    
    public void setLeAdherente(Integer leAdherente) {
        this.leAdherente = leAdherente;
    }

    
    @Column(name="le_cod_osoc")
    public Integer getLeCodOsoc() {
        return this.leCodOsoc;
    }
    
    public void setLeCodOsoc(Integer leCodOsoc) {
        this.leCodOsoc = leCodOsoc;
    }

    
    @Column(name="le_afjp_vol", precision=13)
    public BigDecimal getLeAfjpVol() {
        return this.leAfjpVol;
    }
    
    public void setLeAfjpVol(BigDecimal leAfjpVol) {
        this.leAfjpVol = leAfjpVol;
    }

    
    @Column(name="le_sem_sfam", precision=13)
    public BigDecimal getLeSemSfam() {
        return this.leSemSfam;
    }
    
    public void setLeSemSfam(BigDecimal leSemSfam) {
        this.leSemSfam = leSemSfam;
    }

    
    @Column(name="le_cod_gananc")
    public Short getLeCodGananc() {
        return this.leCodGananc;
    }
    
    public void setLeCodGananc(Short leCodGananc) {
        this.leCodGananc = leCodGananc;
    }

    
    @Column(name="le_cod_accidente")
    public Short getLeCodAccidente() {
        return this.leCodAccidente;
    }
    
    public void setLeCodAccidente(Short leCodAccidente) {
        this.leCodAccidente = leCodAccidente;
    }

    
    @Column(name="le_imp_cuota", precision=10)
    public BigDecimal getLeImpCuota() {
        return this.leImpCuota;
    }
    
    public void setLeImpCuota(BigDecimal leImpCuota) {
        this.leImpCuota = leImpCuota;
    }

    
    @Column(name="le_origen_prest")
    public Integer getLeOrigenPrest() {
        return this.leOrigenPrest;
    }
    
    public void setLeOrigenPrest(Integer leOrigenPrest) {
        this.leOrigenPrest = leOrigenPrest;
    }

    
    @Column(name="le_otros")
    public Short getLeOtros() {
        return this.leOtros;
    }
    
    public void setLeOtros(Short leOtros) {
        this.leOtros = leOtros;
    }

    
    @Column(name="le_otros1")
    public Short getLeOtros1() {
        return this.leOtros1;
    }
    
    public void setLeOtros1(Short leOtros1) {
        this.leOtros1 = leOtros1;
    }

    
    @Column(name="le_banco")
    public Short getLeBanco() {
        return this.leBanco;
    }
    
    public void setLeBanco(Short leBanco) {
        this.leBanco = leBanco;
    }

    
    @Column(name="le_tipo_cta")
    public Short getLeTipoCta() {
        return this.leTipoCta;
    }
    
    public void setLeTipoCta(Short leTipoCta) {
        this.leTipoCta = leTipoCta;
    }

    
    @Column(name="le_nro_cta", precision=10, scale=0)
    public Long getLeNroCta() {
        return this.leNroCta;
    }
    
    public void setLeNroCta(Long leNroCta) {
        this.leNroCta = leNroCta;
    }

    
    @Column(name="le_ult_ingreso")
    public Integer getLeUltIngreso() {
        return this.leUltIngreso;
    }
    
    public void setLeUltIngreso(Integer leUltIngreso) {
        this.leUltIngreso = leUltIngreso;
    }

    
    @Column(name="le_vto_contrat")
    public Integer getLeVtoContrat() {
        return this.leVtoContrat;
    }
    
    public void setLeVtoContrat(Integer leVtoContrat) {
        this.leVtoContrat = leVtoContrat;
    }

    
    @Column(name="le_estado")
    public Short getLeEstado() {
        return this.leEstado;
    }
    
    public void setLeEstado(Short leEstado) {
        this.leEstado = leEstado;
    }

    
    @Column(name="le_estado_trabaja")
    public Short getLeEstadoTrabaja() {
        return this.leEstadoTrabaja;
    }
    
    public void setLeEstadoTrabaja(Short leEstadoTrabaja) {
        this.leEstadoTrabaja = leEstadoTrabaja;
    }

    
    @Column(name="le_desde_x")
    public Integer getLeDesdeX() {
        return this.leDesdeX;
    }
    
    public void setLeDesdeX(Integer leDesdeX) {
        this.leDesdeX = leDesdeX;
    }

    
    @Column(name="le_hasta_x")
    public Integer getLeHastaX() {
        return this.leHastaX;
    }
    
    public void setLeHastaX(Integer leHastaX) {
        this.leHastaX = leHastaX;
    }

    
    @Column(name="le_maternidad")
    public Short getLeMaternidad() {
        return this.leMaternidad;
    }
    
    public void setLeMaternidad(Short leMaternidad) {
        this.leMaternidad = leMaternidad;
    }

    
    @Column(name="le_turno_fijo", length=1)
    public String getLeTurnoFijo() {
        return this.leTurnoFijo;
    }
    
    public void setLeTurnoFijo(String leTurnoFijo) {
        this.leTurnoFijo = leTurnoFijo;
    }

    
    @Column(name="le_cod_uniforme")
    public Short getLeCodUniforme() {
        return this.leCodUniforme;
    }
    
    public void setLeCodUniforme(Short leCodUniforme) {
        this.leCodUniforme = leCodUniforme;
    }

    
    @Column(name="le_prorrata")
    public Short getLeProrrata() {
        return this.leProrrata;
    }
    
    public void setLeProrrata(Short leProrrata) {
        this.leProrrata = leProrrata;
    }

    
    @Column(name="le_vacac_pagas", precision=8)
    public BigDecimal getLeVacacPagas() {
        return this.leVacacPagas;
    }
    
    public void setLeVacacPagas(BigDecimal leVacacPagas) {
        this.leVacacPagas = leVacacPagas;
    }

    
    @Column(name="le_pago_sfam")
    public Short getLePagoSfam() {
        return this.lePagoSfam;
    }
    
    public void setLePagoSfam(Short lePagoSfam) {
        this.lePagoSfam = lePagoSfam;
    }




}


