package entitie;
// Generated 02-oct-2015 16:45:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,schema="public"
)
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private String apellido;
     private String nombre;
     private Date fechaNacimiento;
     private Integer dni;
     private String cuilCuit;
     private String estado;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Persona() {
    }

	
    public Persona(int idPersona, String cuilCuit) {
        this.idPersona = idPersona;
        this.cuilCuit = cuilCuit;
    }
    public Persona(int idPersona, String apellido, String nombre, Date fechaNacimiento, Integer dni, String cuilCuit, String estado, Set<Direccion> direccions) {
       this.idPersona = idPersona;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.dni = dni;
       this.cuilCuit = cuilCuit;
       this.estado = estado;
       this.direccions = direccions;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "persona_seq")
     @SequenceGenerator(name = "persona_seq", sequenceName = "Persona_id_persona_seq", allocationSize = 1)
    @Column(name="id_persona", unique=true, nullable=false)
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    
    @Column(name="apellido")
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_nacimiento", length=29)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="dni")
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }

    
    @Column(name="cuil_cuit", nullable=false)
    public String getCuilCuit() {
        return this.cuilCuit;
    }
    
    public void setCuilCuit(String cuilCuit) {
        this.cuilCuit = cuilCuit;
    }

    
    @Column(name="estado")
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


